[workspace]
resolver = "2"
members = [
    "crates/puffgres-cli",
    "crates/puffgres-config",
    "crates/puffgres-core",
    "crates/puffgres-tp",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/lucasgelfond/puffgres"

[workspace.dependencies]
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
thiserror = "1.0"
rs-puff = "0.1"
puffgres-core = { path = "crates/puffgres-core" }
