[package]
name = "puffgres-tp"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
rs-puff = { workspace = true }
puffgres-core = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
